kind: Namespace
apiVersion: v1
metadata:
  name: api
  labels:
    name: api

---

kind: Namespace
apiVersion: v1
metadata:
  name: alpine-nginx
  labels:
    name: alpine-nginx

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentnodejs
  namespace: api
  labels: 
    app: nodejs 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
     labels:
        app: nodejs
    spec:
      containers:
      - image: vibpositive/my_fist_gabriel_oliveira_microservice:1.0.3
        name: nginx
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m" 

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: alpine-nginx
  name: json-request
data:
  request.json: |
    {
      "name": "Some Random Data",
      "age": 99,
      "nationality": "Martian",
      "visited_countries": ["Greece, Planet earth"]
    }
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-nginx
  namespace: alpine-nginx
  labels: 
    app: alpine-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
     labels:
        app: nodejs
    spec:
      containers:
      - image: byrnedo/alpine-curl
        command:
        - /bin/sh
        - "-c"
        - "while true; do 
            curl -X 'GET' \
              'serviceapi.api.svc.cluster.local/myinfo' \
              -H 'accept: application/json' \
              -H 'Content-Type: application/json' \
              -d @/opt/SBA/request.json >> /html/index.html && sleep 5;
          done"
        name: alpine
        volumeMounts:
        - mountPath: /html
          name: html-volume
        - mountPath: /opt/SBA/scripts/
          name: my-config-map
        resources:
          requests:
            memory: "64Mi"
            cpu: "8"
          limits:
            memory: "128Mi"
            cpu: "500m"

      - image: nginx
        name: nginxhtml
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html-volume
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "4"
          limits:
            memory: "128Mi"
            cpu: "4"

      volumes:
      - name: html-volume
        emptyDir: {}
      - name: json-request
        configMap:
          name: json-request

---

apiVersion: v1
kind: Service
metadata:
  name: serviceapi
  namespace: api
spec:
  selector:
    app: some-app
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      # TODO: need to check if this fails, as port does not exist in container
      targetPort: 9090

